repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-ast
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
    - id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: ^tests/
    args: [--config=.flake8,]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    exclude: ^tests/
    args: [--rcfile=.pylintrc, --errors-only]
