name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      - name: Build Docker image
        run: |
          docker build -t demotest .
        working-directory: .

      - name: Test with Docker
        run: |
          docker run --rm -it demotest
        working-directory: .
