name: CI

on:
  pull_request:
    branches: [main, main2]
  push:
    branches: [main2]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Install project
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v

      - name: Check code formatting with black
        run: |
          pip install black
          black --check --diff .

      - name: Check code style with isort
        run: |
          pip install isort
          isort --check-only --diff .
